# Generated by Django 5.0.8 on 2024-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('gl_date', models.DateField()),
                ('line_desc', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
